-- ============================================================
-- Vetted Migration 010 — Add lead_ic + founder seniority levels
--                        + comprehensive dictionary (400+ patterns)
--
-- Changes:
-- 1. Adds intern, entry, senior_ic, lead_ic, founder to seniority_level enum
-- 2. Migrates existing data: student→intern, lead→lead_ic
-- 3. Restructures seniority_rules table (rename columns, add function_hint/active)
-- 4. Replaces sparse 73-rule seed with comprehensive 400+ pattern dictionary
-- 5. Updates seniority_dictionary rank_order for new levels
--
-- New enum (9 active values, 2 deprecated):
--   unknown(0) < intern(1) < entry(2) < individual_contributor(3) <
--   senior_ic(4) < lead_ic(5) < founder(6) < manager(7) < executive(8)
--   [student(1) and lead(5) kept for backward compat but deprecated]
-- ============================================================

-- ── 1. Add new enum values ──────────────────────────────────────────────────

ALTER TYPE seniority_level ADD VALUE IF NOT EXISTS 'intern';
ALTER TYPE seniority_level ADD VALUE IF NOT EXISTS 'entry';
ALTER TYPE seniority_level ADD VALUE IF NOT EXISTS 'senior_ic';
ALTER TYPE seniority_level ADD VALUE IF NOT EXISTS 'lead_ic';
ALTER TYPE seniority_level ADD VALUE IF NOT EXISTS 'founder';

-- ── 2. Migrate existing data ────────────────────────────────────────────────

UPDATE person_experiences SET seniority_normalized = 'intern' WHERE seniority_normalized = 'student';
UPDATE person_experiences SET seniority_normalized = 'lead_ic' WHERE seniority_normalized = 'lead';
UPDATE people SET highest_seniority_reached = 'intern' WHERE highest_seniority_reached = 'student';
UPDATE people SET highest_seniority_reached = 'lead_ic' WHERE highest_seniority_reached = 'lead';

-- ── 3. Update seniority_dictionary ──────────────────────────────────────────

DELETE FROM seniority_dictionary;
INSERT INTO seniority_dictionary (seniority_normalized, rank_order, description, active) VALUES
  ('unknown', 0, 'No seniority data', true),
  ('intern', 1, 'Internship, co-op, student worker', true),
  ('entry', 2, 'Junior, associate, new grad', true),
  ('individual_contributor', 3, 'Mid-level IC', true),
  ('senior_ic', 4, 'Senior IC', true),
  ('lead_ic', 5, 'Staff, principal, architect, tech lead', true),
  ('founder', 6, 'Company founder or co-founder', true),
  ('manager', 7, 'People manager, director', true),
  ('executive', 8, 'VP, C-suite, Head-of', true),
  ('student', 1, 'DEPRECATED — use intern', false),
  ('lead', 5, 'DEPRECATED — use lead_ic', false);

-- ── 4. Restructure seniority_rules table ────────────────────────────────────

TRUNCATE seniority_rules;
ALTER TABLE seniority_rules RENAME COLUMN pattern TO title_pattern;
ALTER TABLE seniority_rules RENAME COLUMN seniority_normalized TO seniority_level;
ALTER TABLE seniority_rules ADD COLUMN IF NOT EXISTS function_hint TEXT;
ALTER TABLE seniority_rules ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE seniority_rules DROP COLUMN IF EXISTS match_type;
ALTER TABLE seniority_rules DROP COLUMN IF EXISTS notes;

-- ── 5. Re-seed comprehensive dictionary ─────────────────────────────────────

-- ============================================================
-- ENGINEERING — all flavors
-- ============================================================

INSERT INTO seniority_rules (title_pattern, seniority_level, function_hint, priority, active) VALUES

-- Intern
('intern', 'intern', 'engineering', 1, true),
('software engineering intern', 'intern', 'engineering', 1, true),
('swe intern', 'intern', 'engineering', 1, true),
('engineering intern', 'intern', 'engineering', 1, true),
('software developer intern', 'intern', 'engineering', 1, true),
('data engineering intern', 'intern', 'engineering', 1, true),
('ml intern', 'intern', 'engineering', 1, true),
('research intern', 'intern', 'engineering', 1, true),
('infrastructure intern', 'intern', 'engineering', 1, true),
('devops intern', 'intern', 'engineering', 1, true),

-- Entry
('associate software engineer', 'entry', 'engineering', 1, true),
('associate engineer', 'entry', 'engineering', 1, true),
('associate developer', 'entry', 'engineering', 1, true),
('junior software engineer', 'entry', 'engineering', 1, true),
('junior engineer', 'entry', 'engineering', 1, true),
('junior developer', 'entry', 'engineering', 1, true),
('junior backend engineer', 'entry', 'engineering', 1, true),
('junior frontend engineer', 'entry', 'engineering', 1, true),
('software engineer i', 'entry', 'engineering', 1, true),
('software engineer 1', 'entry', 'engineering', 1, true),
('sde i', 'entry', 'engineering', 1, true),
('sde 1', 'entry', 'engineering', 1, true),
('swe i', 'entry', 'engineering', 1, true),
('swe 1', 'entry', 'engineering', 1, true),
('engineer i', 'entry', 'engineering', 1, true),
('engineer 1', 'entry', 'engineering', 1, true),
('new grad software engineer', 'entry', 'engineering', 1, true),
('new grad engineer', 'entry', 'engineering', 1, true),
('graduate software engineer', 'entry', 'engineering', 1, true),
('software development engineer i', 'entry', 'engineering', 1, true),
('google l3', 'entry', 'engineering', 1, true),
('l3 software engineer', 'entry', 'engineering', 1, true),
('meta e3', 'entry', 'engineering', 1, true),
('e3 software engineer', 'entry', 'engineering', 1, true),

-- Individual contributor (flat mid)
('software engineer', 'individual_contributor', 'engineering', 1, true),
('software developer', 'individual_contributor', 'engineering', 1, true),
('engineer', 'individual_contributor', 'engineering', 3, true),
('developer', 'individual_contributor', 'engineering', 3, true),
('full stack engineer', 'individual_contributor', 'engineering', 1, true),
('fullstack engineer', 'individual_contributor', 'engineering', 1, true),
('full-stack engineer', 'individual_contributor', 'engineering', 1, true),
('full stack developer', 'individual_contributor', 'engineering', 1, true),
('fullstack developer', 'individual_contributor', 'engineering', 1, true),
('backend engineer', 'individual_contributor', 'engineering', 1, true),
('back end engineer', 'individual_contributor', 'engineering', 1, true),
('backend developer', 'individual_contributor', 'engineering', 1, true),
('back-end developer', 'individual_contributor', 'engineering', 1, true),
('frontend engineer', 'individual_contributor', 'engineering', 1, true),
('front end engineer', 'individual_contributor', 'engineering', 1, true),
('frontend developer', 'individual_contributor', 'engineering', 1, true),
('front-end developer', 'individual_contributor', 'engineering', 1, true),
('mobile engineer', 'individual_contributor', 'engineering', 1, true),
('ios engineer', 'individual_contributor', 'engineering', 1, true),
('ios developer', 'individual_contributor', 'engineering', 1, true),
('android engineer', 'individual_contributor', 'engineering', 1, true),
('android developer', 'individual_contributor', 'engineering', 1, true),
('mobile developer', 'individual_contributor', 'engineering', 1, true),
('data engineer', 'individual_contributor', 'engineering', 1, true),
('machine learning engineer', 'individual_contributor', 'engineering', 1, true),
('ml engineer', 'individual_contributor', 'engineering', 1, true),
('ai engineer', 'individual_contributor', 'engineering', 1, true),
('ai/ml engineer', 'individual_contributor', 'engineering', 1, true),
('devops engineer', 'individual_contributor', 'engineering', 1, true),
('site reliability engineer', 'individual_contributor', 'engineering', 1, true),
('sre', 'individual_contributor', 'engineering', 1, true),
('infrastructure engineer', 'individual_contributor', 'engineering', 1, true),
('infra engineer', 'individual_contributor', 'engineering', 1, true),
('platform engineer', 'individual_contributor', 'engineering', 1, true),
('security engineer', 'individual_contributor', 'engineering', 1, true),
('embedded engineer', 'individual_contributor', 'engineering', 1, true),
('firmware engineer', 'individual_contributor', 'engineering', 1, true),
('systems engineer', 'individual_contributor', 'engineering', 1, true),
('software development engineer', 'individual_contributor', 'engineering', 1, true),
('developer relations engineer', 'individual_contributor', 'engineering', 1, true),
('developer advocate', 'individual_contributor', 'engineering', 1, true),
('software engineer ii', 'individual_contributor', 'engineering', 1, true),
('software engineer 2', 'individual_contributor', 'engineering', 1, true),
('sde ii', 'individual_contributor', 'engineering', 1, true),
('sde 2', 'individual_contributor', 'engineering', 1, true),
('swe ii', 'individual_contributor', 'engineering', 1, true),
('swe 2', 'individual_contributor', 'engineering', 1, true),
('engineer ii', 'individual_contributor', 'engineering', 1, true),
('engineer 2', 'individual_contributor', 'engineering', 1, true),
('google l4', 'individual_contributor', 'engineering', 1, true),
('l4 software engineer', 'individual_contributor', 'engineering', 1, true),
('meta e4', 'individual_contributor', 'engineering', 1, true),
('e4 software engineer', 'individual_contributor', 'engineering', 1, true),
('amazon sde ii', 'individual_contributor', 'engineering', 1, true),
('software development engineer ii', 'individual_contributor', 'engineering', 1, true),

-- Senior IC
('senior software engineer', 'senior_ic', 'engineering', 1, true),
('senior engineer', 'senior_ic', 'engineering', 1, true),
('senior developer', 'senior_ic', 'engineering', 1, true),
('senior full stack engineer', 'senior_ic', 'engineering', 1, true),
('senior fullstack engineer', 'senior_ic', 'engineering', 1, true),
('senior backend engineer', 'senior_ic', 'engineering', 1, true),
('senior backend developer', 'senior_ic', 'engineering', 1, true),
('senior frontend engineer', 'senior_ic', 'engineering', 1, true),
('senior frontend developer', 'senior_ic', 'engineering', 1, true),
('senior mobile engineer', 'senior_ic', 'engineering', 1, true),
('senior ios engineer', 'senior_ic', 'engineering', 1, true),
('senior android engineer', 'senior_ic', 'engineering', 1, true),
('senior data engineer', 'senior_ic', 'engineering', 1, true),
('senior machine learning engineer', 'senior_ic', 'engineering', 1, true),
('senior ml engineer', 'senior_ic', 'engineering', 1, true),
('senior ai engineer', 'senior_ic', 'engineering', 1, true),
('senior devops engineer', 'senior_ic', 'engineering', 1, true),
('senior site reliability engineer', 'senior_ic', 'engineering', 1, true),
('senior sre', 'senior_ic', 'engineering', 1, true),
('senior infrastructure engineer', 'senior_ic', 'engineering', 1, true),
('senior platform engineer', 'senior_ic', 'engineering', 1, true),
('senior security engineer', 'senior_ic', 'engineering', 1, true),
('senior embedded engineer', 'senior_ic', 'engineering', 1, true),
('senior systems engineer', 'senior_ic', 'engineering', 1, true),
('senior software development engineer', 'senior_ic', 'engineering', 1, true),
('software engineer iii', 'senior_ic', 'engineering', 1, true),
('software engineer 3', 'senior_ic', 'engineering', 1, true),
('sde iii', 'senior_ic', 'engineering', 1, true),
('sde 3', 'senior_ic', 'engineering', 1, true),
('swe iii', 'senior_ic', 'engineering', 1, true),
('swe 3', 'senior_ic', 'engineering', 1, true),
('engineer iii', 'senior_ic', 'engineering', 1, true),
('engineer 3', 'senior_ic', 'engineering', 1, true),
('google l5', 'senior_ic', 'engineering', 1, true),
('l5 software engineer', 'senior_ic', 'engineering', 1, true),
('meta e5', 'senior_ic', 'engineering', 1, true),
('e5 software engineer', 'senior_ic', 'engineering', 1, true),
('amazon sde iii', 'senior_ic', 'engineering', 1, true),
('software development engineer iii', 'senior_ic', 'engineering', 1, true),

-- Lead IC
('staff engineer', 'lead_ic', 'engineering', 1, true),
('staff software engineer', 'lead_ic', 'engineering', 1, true),
('staff backend engineer', 'lead_ic', 'engineering', 1, true),
('staff frontend engineer', 'lead_ic', 'engineering', 1, true),
('staff data engineer', 'lead_ic', 'engineering', 1, true),
('staff ml engineer', 'lead_ic', 'engineering', 1, true),
('staff infrastructure engineer', 'lead_ic', 'engineering', 1, true),
('staff platform engineer', 'lead_ic', 'engineering', 1, true),
('staff devops engineer', 'lead_ic', 'engineering', 1, true),
('staff security engineer', 'lead_ic', 'engineering', 1, true),
('staff mobile engineer', 'lead_ic', 'engineering', 1, true),
('lead engineer', 'lead_ic', 'engineering', 1, true),
('lead software engineer', 'lead_ic', 'engineering', 1, true),
('lead backend engineer', 'lead_ic', 'engineering', 1, true),
('lead frontend engineer', 'lead_ic', 'engineering', 1, true),
('lead data engineer', 'lead_ic', 'engineering', 1, true),
('lead ml engineer', 'lead_ic', 'engineering', 1, true),
('lead infrastructure engineer', 'lead_ic', 'engineering', 1, true),
('principal engineer', 'lead_ic', 'engineering', 1, true),
('principal software engineer', 'lead_ic', 'engineering', 1, true),
('principal backend engineer', 'lead_ic', 'engineering', 1, true),
('principal data engineer', 'lead_ic', 'engineering', 1, true),
('principal ml engineer', 'lead_ic', 'engineering', 1, true),
('principal infrastructure engineer', 'lead_ic', 'engineering', 1, true),
('software architect', 'lead_ic', 'engineering', 1, true),
('architect', 'lead_ic', 'engineering', 2, true),
('solutions architect', 'lead_ic', 'engineering', 1, true),
('enterprise architect', 'lead_ic', 'engineering', 1, true),
('cloud architect', 'lead_ic', 'engineering', 1, true),
('data architect', 'lead_ic', 'engineering', 1, true),
('technical lead', 'lead_ic', 'engineering', 1, true),
('tech lead', 'lead_ic', 'engineering', 1, true),
('tl', 'lead_ic', 'engineering', 2, true),
('tech lead manager', 'lead_ic', 'engineering', 1, true),
('technical lead manager', 'lead_ic', 'engineering', 1, true),
('tlm', 'lead_ic', 'engineering', 1, true),
('senior staff engineer', 'lead_ic', 'engineering', 1, true),
('senior staff software engineer', 'lead_ic', 'engineering', 1, true),
('senior principal engineer', 'lead_ic', 'engineering', 1, true),
('distinguished engineer', 'lead_ic', 'engineering', 1, true),
('founding engineer', 'lead_ic', 'engineering', 1, true),
('software engineer iv', 'lead_ic', 'engineering', 1, true),
('software engineer 4', 'lead_ic', 'engineering', 1, true),
('engineer iv', 'lead_ic', 'engineering', 1, true),
('engineer 4', 'lead_ic', 'engineering', 1, true),
('google l6', 'lead_ic', 'engineering', 1, true),
('l6 software engineer', 'lead_ic', 'engineering', 1, true),
('meta e6', 'lead_ic', 'engineering', 1, true),
('e6 software engineer', 'lead_ic', 'engineering', 1, true),
('principal sde', 'lead_ic', 'engineering', 1, true),
('principal software development engineer', 'lead_ic', 'engineering', 1, true),

-- Manager
('engineering manager', 'manager', 'engineering', 1, true),
('em', 'manager', 'engineering', 2, true),
('senior engineering manager', 'manager', 'engineering', 1, true),
('manager of engineering', 'manager', 'engineering', 1, true),
('engineering director', 'manager', 'engineering', 1, true),
('director of engineering', 'manager', 'engineering', 1, true),
('senior director of engineering', 'manager', 'engineering', 1, true),
('director of software engineering', 'manager', 'engineering', 1, true),
('google l7', 'manager', 'engineering', 1, true),
('meta e7', 'manager', 'engineering', 1, true),

-- Executive
('vp of engineering', 'executive', 'engineering', 1, true),
('vp engineering', 'executive', 'engineering', 1, true),
('vice president of engineering', 'executive', 'engineering', 1, true),
('svp of engineering', 'executive', 'engineering', 1, true),
('evp of engineering', 'executive', 'engineering', 1, true),
('cto', 'executive', 'engineering', 1, true),
('chief technology officer', 'executive', 'engineering', 1, true),
('head of engineering', 'executive', 'engineering', 1, true),
('google l8', 'executive', 'engineering', 1, true),
('google fellow', 'executive', 'engineering', 1, true),
('meta e8', 'executive', 'engineering', 1, true),
('amazon fellow', 'executive', 'engineering', 1, true);

-- ============================================================
-- PRODUCT MANAGEMENT
-- ============================================================

INSERT INTO seniority_rules (title_pattern, seniority_level, function_hint, priority, active) VALUES
('product management intern', 'intern', 'product_management', 1, true),
('product intern', 'intern', 'product_management', 1, true),
('pm intern', 'intern', 'product_management', 1, true),
('associate product manager', 'entry', 'product_management', 1, true),
('apm', 'entry', 'product_management', 1, true),
('junior product manager', 'entry', 'product_management', 1, true),
('product manager i', 'entry', 'product_management', 1, true),
('product manager 1', 'entry', 'product_management', 1, true),
('pm i', 'entry', 'product_management', 1, true),
('product coordinator', 'entry', 'product_management', 1, true),
('product analyst', 'entry', 'product_management', 2, true),
('rotational product manager', 'entry', 'product_management', 1, true),
('product manager', 'individual_contributor', 'product_management', 1, true),
('pm', 'individual_contributor', 'product_management', 2, true),
('product manager ii', 'individual_contributor', 'product_management', 1, true),
('product manager 2', 'individual_contributor', 'product_management', 1, true),
('technical product manager', 'individual_contributor', 'product_management', 1, true),
('growth product manager', 'individual_contributor', 'product_management', 1, true),
('data product manager', 'individual_contributor', 'product_management', 1, true),
('platform product manager', 'individual_contributor', 'product_management', 1, true),
('senior product manager', 'senior_ic', 'product_management', 1, true),
('senior pm', 'senior_ic', 'product_management', 1, true),
('spm', 'senior_ic', 'product_management', 1, true),
('product manager iii', 'senior_ic', 'product_management', 1, true),
('product manager 3', 'senior_ic', 'product_management', 1, true),
('senior technical product manager', 'senior_ic', 'product_management', 1, true),
('staff product manager', 'lead_ic', 'product_management', 1, true),
('principal product manager', 'lead_ic', 'product_management', 1, true),
('lead product manager', 'lead_ic', 'product_management', 1, true),
('group product manager', 'lead_ic', 'product_management', 1, true),
('gpm', 'lead_ic', 'product_management', 1, true),
('product lead', 'lead_ic', 'product_management', 1, true),
('product manager iv', 'lead_ic', 'product_management', 1, true),
('senior staff product manager', 'lead_ic', 'product_management', 1, true),
('director of product', 'manager', 'product_management', 1, true),
('director of product management', 'manager', 'product_management', 1, true),
('product director', 'manager', 'product_management', 1, true),
('senior director of product', 'manager', 'product_management', 1, true),
('vp of product', 'executive', 'product_management', 1, true),
('vp product', 'executive', 'product_management', 1, true),
('vice president of product', 'executive', 'product_management', 1, true),
('chief product officer', 'executive', 'product_management', 1, true),
('cpo', 'executive', 'product_management', 2, true),
('head of product', 'executive', 'product_management', 1, true),
('svp of product', 'executive', 'product_management', 1, true);

-- ============================================================
-- PRODUCT DESIGN
-- ============================================================

INSERT INTO seniority_rules (title_pattern, seniority_level, function_hint, priority, active) VALUES
('design intern', 'intern', 'product_design', 1, true),
('ux design intern', 'intern', 'product_design', 1, true),
('product design intern', 'intern', 'product_design', 1, true),
('associate designer', 'entry', 'product_design', 1, true),
('associate product designer', 'entry', 'product_design', 1, true),
('associate ux designer', 'entry', 'product_design', 1, true),
('junior designer', 'entry', 'product_design', 1, true),
('junior product designer', 'entry', 'product_design', 1, true),
('junior ux designer', 'entry', 'product_design', 1, true),
('design coordinator', 'entry', 'product_design', 1, true),
('ux designer i', 'entry', 'product_design', 1, true),
('product designer', 'individual_contributor', 'product_design', 1, true),
('ux designer', 'individual_contributor', 'product_design', 1, true),
('ui designer', 'individual_contributor', 'product_design', 1, true),
('ui/ux designer', 'individual_contributor', 'product_design', 1, true),
('interaction designer', 'individual_contributor', 'product_design', 1, true),
('visual designer', 'individual_contributor', 'product_design', 1, true),
('designer', 'individual_contributor', 'product_design', 3, true),
('brand designer', 'individual_contributor', 'product_design', 1, true),
('motion designer', 'individual_contributor', 'product_design', 1, true),
('ux researcher', 'individual_contributor', 'product_design', 1, true),
('user researcher', 'individual_contributor', 'product_design', 1, true),
('content designer', 'individual_contributor', 'product_design', 1, true),
('senior product designer', 'senior_ic', 'product_design', 1, true),
('senior ux designer', 'senior_ic', 'product_design', 1, true),
('senior ui designer', 'senior_ic', 'product_design', 1, true),
('senior designer', 'senior_ic', 'product_design', 1, true),
('senior interaction designer', 'senior_ic', 'product_design', 1, true),
('senior visual designer', 'senior_ic', 'product_design', 1, true),
('senior brand designer', 'senior_ic', 'product_design', 1, true),
('senior ux researcher', 'senior_ic', 'product_design', 1, true),
('senior content designer', 'senior_ic', 'product_design', 1, true),
('staff designer', 'lead_ic', 'product_design', 1, true),
('staff product designer', 'lead_ic', 'product_design', 1, true),
('principal designer', 'lead_ic', 'product_design', 1, true),
('principal product designer', 'lead_ic', 'product_design', 1, true),
('lead designer', 'lead_ic', 'product_design', 1, true),
('lead product designer', 'lead_ic', 'product_design', 1, true),
('design lead', 'lead_ic', 'product_design', 1, true),
('ux lead', 'lead_ic', 'product_design', 1, true),
('product design lead', 'lead_ic', 'product_design', 1, true),
('senior staff designer', 'lead_ic', 'product_design', 1, true),
('design manager', 'manager', 'product_design', 1, true),
('product design manager', 'manager', 'product_design', 1, true),
('ux manager', 'manager', 'product_design', 1, true),
('director of design', 'manager', 'product_design', 1, true),
('design director', 'manager', 'product_design', 1, true),
('senior design manager', 'manager', 'product_design', 1, true),
('senior director of design', 'manager', 'product_design', 1, true),
('vp of design', 'executive', 'product_design', 1, true),
('vp design', 'executive', 'product_design', 1, true),
('chief design officer', 'executive', 'product_design', 1, true),
('head of design', 'executive', 'product_design', 1, true),
('head of ux', 'executive', 'product_design', 1, true);

-- ============================================================
-- OPERATIONS
-- ============================================================

INSERT INTO seniority_rules (title_pattern, seniority_level, function_hint, priority, active) VALUES
('operations intern', 'intern', 'operations', 1, true),
('biz ops intern', 'intern', 'operations', 1, true),
('strategy intern', 'intern', 'operations', 1, true),
('growth intern', 'intern', 'operations', 1, true),
('operations associate', 'entry', 'operations', 1, true),
('biz ops associate', 'entry', 'operations', 1, true),
('business operations associate', 'entry', 'operations', 1, true),
('strategy associate', 'entry', 'operations', 1, true),
('operations analyst', 'entry', 'operations', 1, true),
('business analyst', 'entry', 'operations', 2, true),
('analyst', 'entry', 'operations', 3, true),
('revenue operations associate', 'entry', 'operations', 1, true),
('revops associate', 'entry', 'operations', 1, true),
('growth associate', 'entry', 'operations', 1, true),
('ops coordinator', 'entry', 'operations', 1, true),
('operations coordinator', 'entry', 'operations', 1, true),
('bain associate consultant', 'entry', 'operations', 1, true),
('associate consultant', 'entry', 'operations', 1, true),
('mckinsey analyst', 'entry', 'operations', 1, true),
('consulting analyst', 'entry', 'operations', 1, true),
('operations specialist', 'individual_contributor', 'operations', 1, true),
('biz ops specialist', 'individual_contributor', 'operations', 1, true),
('revenue operations specialist', 'individual_contributor', 'operations', 1, true),
('revops specialist', 'individual_contributor', 'operations', 1, true),
('growth analyst', 'individual_contributor', 'operations', 1, true),
('strategy analyst', 'individual_contributor', 'operations', 1, true),
('senior business analyst', 'individual_contributor', 'operations', 1, true),
('finance analyst', 'individual_contributor', 'operations', 1, true),
('financial analyst', 'individual_contributor', 'operations', 1, true),
('consultant', 'individual_contributor', 'operations', 2, true),
('bain consultant', 'individual_contributor', 'operations', 1, true),
('mckinsey associate', 'individual_contributor', 'operations', 1, true),
('strategy consultant', 'individual_contributor', 'operations', 1, true),
('senior operations specialist', 'senior_ic', 'operations', 1, true),
('senior biz ops', 'senior_ic', 'operations', 1, true),
('senior analyst', 'senior_ic', 'operations', 1, true),
('senior strategy analyst', 'senior_ic', 'operations', 1, true),
('senior revenue operations', 'senior_ic', 'operations', 1, true),
('senior revops', 'senior_ic', 'operations', 1, true),
('senior financial analyst', 'senior_ic', 'operations', 1, true),
('senior consultant', 'senior_ic', 'operations', 1, true),
('bain case team leader', 'senior_ic', 'operations', 1, true),
('case team leader', 'senior_ic', 'operations', 1, true),
('mckinsey engagement manager', 'senior_ic', 'operations', 1, true),
('engagement manager', 'senior_ic', 'operations', 2, true),
('biz ops lead', 'lead_ic', 'operations', 1, true),
('strategy lead', 'lead_ic', 'operations', 1, true),
('operations lead', 'lead_ic', 'operations', 1, true),
('revenue operations lead', 'lead_ic', 'operations', 1, true),
('revops lead', 'lead_ic', 'operations', 1, true),
('lead analyst', 'lead_ic', 'operations', 1, true),
('principal analyst', 'lead_ic', 'operations', 1, true),
('mckinsey associate principal', 'lead_ic', 'operations', 1, true),
('associate principal', 'lead_ic', 'operations', 2, true),
('operations manager', 'manager', 'operations', 1, true),
('biz ops manager', 'manager', 'operations', 1, true),
('business operations manager', 'manager', 'operations', 1, true),
('senior operations manager', 'manager', 'operations', 1, true),
('revenue operations manager', 'manager', 'operations', 1, true),
('director of operations', 'manager', 'operations', 1, true),
('operations director', 'manager', 'operations', 1, true),
('director of business operations', 'manager', 'operations', 1, true),
('senior director of operations', 'manager', 'operations', 1, true),
('director of strategy', 'manager', 'operations', 1, true),
('director of revenue operations', 'manager', 'operations', 1, true),
('mckinsey principal', 'manager', 'operations', 1, true),
('bain manager', 'manager', 'operations', 1, true),
('bain principal', 'manager', 'operations', 1, true),
('vp of operations', 'executive', 'operations', 1, true),
('vp operations', 'executive', 'operations', 1, true),
('chief operating officer', 'executive', 'operations', 1, true),
('coo', 'executive', 'operations', 1, true),
('head of operations', 'executive', 'operations', 1, true),
('head of strategy', 'executive', 'operations', 1, true),
('vp of strategy', 'executive', 'operations', 1, true),
('svp of operations', 'executive', 'operations', 1, true),
('mckinsey partner', 'executive', 'operations', 1, true),
('bain partner', 'executive', 'operations', 1, true);

-- ============================================================
-- RECRUITING / TALENT / PEOPLE
-- ============================================================

INSERT INTO seniority_rules (title_pattern, seniority_level, function_hint, priority, active) VALUES
('recruiting intern', 'intern', 'recruiting', 1, true),
('talent acquisition intern', 'intern', 'recruiting', 1, true),
('hr intern', 'intern', 'recruiting', 1, true),
('people ops intern', 'intern', 'recruiting', 1, true),
('recruiting coordinator', 'entry', 'recruiting', 1, true),
('talent coordinator', 'entry', 'recruiting', 1, true),
('hr coordinator', 'entry', 'recruiting', 1, true),
('people operations coordinator', 'entry', 'recruiting', 1, true),
('sourcer', 'entry', 'recruiting', 1, true),
('sourcing specialist', 'entry', 'recruiting', 1, true),
('talent sourcer', 'entry', 'recruiting', 1, true),
('recruiting associate', 'entry', 'recruiting', 1, true),
('talent associate', 'entry', 'recruiting', 1, true),
('junior recruiter', 'entry', 'recruiting', 1, true),
('associate recruiter', 'entry', 'recruiting', 1, true),
('hr associate', 'entry', 'recruiting', 1, true),
('people ops associate', 'entry', 'recruiting', 1, true),
('recruiter i', 'entry', 'recruiting', 1, true),
('recruiter', 'individual_contributor', 'recruiting', 1, true),
('talent acquisition specialist', 'individual_contributor', 'recruiting', 1, true),
('technical recruiter', 'individual_contributor', 'recruiting', 1, true),
('tech recruiter', 'individual_contributor', 'recruiting', 1, true),
('corporate recruiter', 'individual_contributor', 'recruiting', 1, true),
('people ops specialist', 'individual_contributor', 'recruiting', 1, true),
('hr specialist', 'individual_contributor', 'recruiting', 1, true),
('hr generalist', 'individual_contributor', 'recruiting', 1, true),
('people operations specialist', 'individual_contributor', 'recruiting', 1, true),
('recruiter ii', 'individual_contributor', 'recruiting', 1, true),
('talent acquisition partner', 'individual_contributor', 'recruiting', 2, true),
('senior recruiter', 'senior_ic', 'recruiting', 1, true),
('senior technical recruiter', 'senior_ic', 'recruiting', 1, true),
('senior tech recruiter', 'senior_ic', 'recruiting', 1, true),
('senior talent acquisition specialist', 'senior_ic', 'recruiting', 1, true),
('senior people ops specialist', 'senior_ic', 'recruiting', 1, true),
('senior hr generalist', 'senior_ic', 'recruiting', 1, true),
('senior hr specialist', 'senior_ic', 'recruiting', 1, true),
('senior talent acquisition partner', 'senior_ic', 'recruiting', 1, true),
('recruiter iii', 'senior_ic', 'recruiting', 1, true),
('lead recruiter', 'lead_ic', 'recruiting', 1, true),
('recruiting lead', 'lead_ic', 'recruiting', 1, true),
('talent lead', 'lead_ic', 'recruiting', 1, true),
('talent acquisition lead', 'lead_ic', 'recruiting', 1, true),
('principal recruiter', 'lead_ic', 'recruiting', 1, true),
('staff recruiter', 'lead_ic', 'recruiting', 1, true),
('lead technical recruiter', 'lead_ic', 'recruiting', 1, true),
('people ops lead', 'lead_ic', 'recruiting', 1, true),
('hr lead', 'lead_ic', 'recruiting', 1, true),
('recruiting manager', 'manager', 'recruiting', 1, true),
('talent acquisition manager', 'manager', 'recruiting', 1, true),
('people ops manager', 'manager', 'recruiting', 1, true),
('hr manager', 'manager', 'recruiting', 1, true),
('people operations manager', 'manager', 'recruiting', 1, true),
('director of talent', 'manager', 'recruiting', 1, true),
('director of talent acquisition', 'manager', 'recruiting', 1, true),
('director of recruiting', 'manager', 'recruiting', 1, true),
('director of people', 'manager', 'recruiting', 1, true),
('director of people operations', 'manager', 'recruiting', 1, true),
('director of hr', 'manager', 'recruiting', 1, true),
('senior director of talent', 'manager', 'recruiting', 1, true),
('senior director of people', 'manager', 'recruiting', 1, true),
('senior recruiting manager', 'manager', 'recruiting', 1, true),
('vp of people', 'executive', 'recruiting', 1, true),
('vp people', 'executive', 'recruiting', 1, true),
('vp of talent', 'executive', 'recruiting', 1, true),
('vp of hr', 'executive', 'recruiting', 1, true),
('chief people officer', 'executive', 'recruiting', 1, true),
('chief human resources officer', 'executive', 'recruiting', 1, true),
('chro', 'executive', 'recruiting', 1, true),
('head of people', 'executive', 'recruiting', 1, true),
('head of talent', 'executive', 'recruiting', 1, true),
('head of hr', 'executive', 'recruiting', 1, true),
('svp of people', 'executive', 'recruiting', 1, true);

-- ============================================================
-- CROSS-FUNCTION RULES
-- ============================================================

INSERT INTO seniority_rules (title_pattern, seniority_level, function_hint, priority, active) VALUES
-- Founder + exec combos (priority 0 = always wins over bare founder)
('co-founder & cto', 'executive', null, 0, true),
('co-founder and cto', 'executive', null, 0, true),
('cofounder & cto', 'executive', null, 0, true),
('co-founder & ceo', 'executive', null, 0, true),
('co-founder and ceo', 'executive', null, 0, true),
('founder & ceo', 'executive', null, 0, true),
('founder and ceo', 'executive', null, 0, true),
('founder & cto', 'executive', null, 0, true),
('founder and cto', 'executive', null, 0, true),
('co-founder & cpo', 'executive', null, 0, true),
('co-founder & coo', 'executive', null, 0, true),
('founder & coo', 'executive', null, 0, true),
('founder & cfo', 'executive', null, 0, true),

-- Bare founder = founder level
('founder', 'founder', null, 1, true),
('co-founder', 'founder', null, 1, true),
('cofounder', 'founder', null, 1, true),
('co founder', 'founder', null, 1, true),

-- Founding engineer = lead_ic (early employee, not company founder)
('founding engineer', 'lead_ic', 'engineering', 1, true),
('founding member', 'individual_contributor', null, 1, true),
('founding team', 'individual_contributor', null, 1, true),

-- C-suite
('ceo', 'executive', null, 1, true),
('chief executive officer', 'executive', null, 1, true),
('cfo', 'executive', null, 1, true),
('chief financial officer', 'executive', null, 1, true),
('ciso', 'executive', null, 1, true),
('chief information security officer', 'executive', null, 1, true),
('cmo', 'executive', null, 1, true),
('chief marketing officer', 'executive', null, 1, true),
('cro', 'executive', null, 1, true),
('chief revenue officer', 'executive', null, 1, true),

-- Contractor/freelance
('contractor', 'intern', null, 2, true),
('freelancer', 'intern', null, 2, true),
('freelance', 'intern', null, 2, true),

-- Postdoc override (priority 0 always beats generic fellow)
('postdoctoral fellow', 'entry', null, 0, true),
('postdoc', 'entry', null, 0, true),
('postdoctoral researcher', 'entry', null, 0, true),
('postdoctoral associate', 'entry', null, 0, true);
